name: php ci workflow
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        name: Run PHP CI workflow
        steps:
            - uses: actions/checkout@v3
            - name: Set up PHP
              uses: shivammathur/setup-php@v2
              with:
                php-version: '8.1'