name: php ci workflow
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    schedule:
        - cron: "10 10 * * *"
jobs:
    build:
        runs-on: ubuntu-latest
        name: Run PHP CI workflow
        steps: 
            - uses: actions/checkout@v2
            
            